import test from 'node:test';import assert from 'node:assert/strict';
import {reputation,clusters,tokenRisk,fill,tradesFromTransaction,USDC,POLICY,signal} from '../lib/quant.ts';
test('sell without observed inventory cannot create profits',()=>{assert.equal(reputation([{at:1,side:'sell',mint:'x',qty:100,usd:10000}]).pnl,0)});
test('partial exits preserve remaining cost basis',()=>{const r=reputation([{at:1,side:'buy',mint:'x',qty:10,usd:100},{at:2,side:'sell',mint:'x',qty:5,usd:60},{at:3,side:'sell',mint:'x',qty:5,usd:40}]);assert.ok(Math.abs(r.pnl-(-.66))<1e-8);assert.equal(r.roundTrips,2)});
test('low sample scores are ineligible',()=>assert.equal(reputation([{at:1,side:'buy',mint:'x',qty:1,usd:1},{at:2,side:'sell',mint:'x',qty:1,usd:100}]).eligible,false));
test('weak links do not assert ownership; strong links union transitively',()=>{const c=clusters(['a','b','c','d'],[{a:'a',b:'b',strength:'strong'},{a:'b',b:'c',strength:'strong'},{a:'c',b:'d',strength:'weak'}]);assert.equal(c.a,c.c);assert.notEqual(c.a,c.d)});
test('missing security evidence fails closed',()=>assert.equal(tokenRisk({liquidity:1000000}).allowed,false));
test('latency and stale quotes reject imaginary fills',()=>{const o={at:1000,side:'buy',usd:20};assert.equal(fill(o,{at:1500,price:1,liquidity:1e6},1500).status,'pending');assert.equal(fill(o,{at:1500,price:1,liquidity:1e6},3000).status,'failed');assert.equal(fill(o,{at:3000,price:1,liquidity:1e6},100000).status,'failed')});
test('fills pay spread, impact and fees',()=>{const f=fill({at:1000,side:'buy',usd:20},{at:3000,price:1,liquidity:1e6},3000);assert.equal(f.status,'filled');assert.ok(f.qty<20);assert.ok(f.fee>0)});
test('free token receipts are not trades',()=>{const t={meta:{preTokenBalances:[],postTokenBalances:[{owner:'a',mint:'x',uiTokenAmount:{amount:'100',decimals:0}}]},transaction:{message:{accountKeys:[{signer:true,pubkey:'a'}]},signatures:['s']}};assert.deepEqual(tradesFromTransaction(t,1,1),[])});
test('future wallet entries never contribute to a current signal',()=>{const s=signal({mint:'x'},[{wallet:'a',at:2000,side:'buy'}],[{wallet:'a',eligible:true}],{},1000);assert.equal(s.evidence.entries.length,0);assert.equal(s.action,'REJECT')});

test('portfolio replay sizes only known signals and exits with later quotes',async()=>{const {replayPortfolio}=await import('../lib/quant.ts');const s=[{id:'s',mint:'x',at:1000,action:'PAPER_BUY',score:90}];const q=[{mint:'x',at:3000,price:1,liquidity:1e6},{mint:'x',at:5000,price:1.3,liquidity:1e6},{mint:'x',at:7000,price:1.3,liquidity:1e6}];const r=replayPortfolio(s,q,0,10000);assert.equal(r.statistics.closed,1);assert.equal(r.openPositions.length,0);assert.ok(r.cash>1000);assert.equal(r.trades[0].usd,20);assert.ok(r.cash<1006)});
test('missing future quote cannot create an exit or future profit',async()=>{const {replayPortfolio}=await import('../lib/quant.ts');const r=replayPortfolio([{mint:'x',at:1000,action:'PAPER_BUY',score:90}],[{mint:'x',at:500,price:0.1,liquidity:1e6}],0,10000);assert.equal(r.trades.length,0);assert.equal(r.cash,1000);assert.equal(r.unresolvedOrders.length,1)});
test('pending orders count toward portfolio exposure',async()=>{const {replayPortfolio}=await import('../lib/quant.ts');const signals=Array.from({length:20},(_,i)=>({mint:'t'+i,at:1000,action:'PAPER_BUY',score:90}));const r=replayPortfolio(signals,[],0,10000);assert.ok(r.unresolvedOrders.reduce((s,o)=>s+o.usd,0)<=150)});
