import { readFileSync } from "node:fs";
import { strategy } from "./strategy.mjs";
export const USDC = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";
export const TOKEN = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA";
export const ASSOCIATED = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL";
export const JUPITER = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4";
export function integer(value,name,min,max){const n=Number(value);if(!Number.isSafeInteger(n)||n<min||n>max)throw Error(`Invalid ${name}`);return n}
export function config(e=process.env){const mode=e.TRADING_MODE??"paper",c={mode,disableDiscovery:e.DISABLE_DISCOVERY==="true",port:integer(e.PORT??8080,"PORT",1,65535),db:e.DATABASE_PATH??":memory:",persistence:e.PERSISTENCE_BACKEND??(e.SUPABASE_URL?"supabase":"sqlite"),supabaseURL:e.SUPABASE_URL??"",supabaseKey:e.SUPABASE_SERVICE_ROLE_KEY??"",rpc:e.SOLANA_RPC_URL??"https://api.mainnet-beta.solana.com",apiToken:e.ADMIN_TOKEN??"",webhookToken:e.INGEST_TOKEN??"",jupiterKey:e.JUPITER_API_KEY??"",signerURL:e.SIGNER_URL??"http://signer:8090",signerTransport:e.SIGNER_TRANSPORT??"http",signerToken:e.SIGNER_TOKEN??"",assetsFile:e.ASSET_POLICY_FILE??"/config/approved-assets.json",paperBalance:integer(e.PAPER_BALANCE_USDC??1000,"PAPER_BALANCE_USDC",1,1000000),pollMs:integer(e.POLL_MS??1000,"POLL_MS",250,60000),signerEnabled:e.SIGNER_ENABLE_LIVE==="true",keyPath:e.SIGNER_KEYPAIR_FILE??"",keyBase64:e.SIGNER_KEYPAIR_BASE64??"",budget:integer(e.LIVE_BUDGET_USDC??0,"LIVE_BUDGET_USDC",0,1000000),maxOrder:integer(e.LIVE_MAX_ORDER_USDC??0,"LIVE_MAX_ORDER_USDC",0,100000),maxDaily:integer(e.LIVE_DAILY_BUY_LIMIT_USDC??0,"LIVE_DAILY_BUY_LIMIT_USDC",0,1000000),maxLoss:integer(e.LIVE_DAILY_LOSS_LIMIT_USDC??0,"LIVE_DAILY_LOSS_LIMIT_USDC",0,100000),maxLamports:integer(e.MAX_NATIVE_COST_LAMPORTS??5000000,"MAX_NATIVE_COST_LAMPORTS",5000,10000000),minReserve:integer(e.MIN_SOL_RESERVE_LAMPORTS??10000000,"MIN_SOL_RESERVE_LAMPORTS",1000000,1000000000),approvalHash:e.LIVE_APPROVAL_SHA256??"",discoveryPrograms:(e.DISCOVERY_PROGRAMS??JUPITER).split(",").filter(Boolean)};if(!["paper","live"].includes(c.mode))throw Error("TRADING_MODE must be paper or live");if(!["sqlite","supabase"].includes(c.persistence))throw Error("PERSISTENCE_BACKEND must be sqlite or supabase");if(c.persistence==="supabase"&&(!c.supabaseURL||c.supabaseKey.length<20))throw Error("Supabase persistence requires SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY");if(c.mode==="live"&&c.persistence==="supabase")throw Error("Supabase cache persistence is paper-only; live mode requires the isolated durable signer design");for(const url of[c.rpc])if(new URL(url).protocol!=="https:")throw Error("RPC must use HTTPS");return c}
export function validAssetPolicy(list){return Array.isArray(list)?list.filter(x=>typeof x.mint==="string"&&/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(x.mint)&&Number.isFinite(x.expiresAt)&&x.expiresAt>Date.now()&&typeof x.reviewedBy==="string"&&x.reviewedBy.length>0&&typeof x.evidence==="string"&&x.evidence.length>=20):[]}
export function assets(c){if(Array.isArray(c.runtimeAssets))return validAssetPolicy(c.runtimeAssets);try{return validAssetPolicy(JSON.parse(readFileSync(c.assetsFile,"utf8")))}catch{return[]}}
export function liveConfiguration(c,assetPolicy=assets(c)){const s=strategy();return [["Explicit live mode",c.mode==="live"],["Signer enabled",c.signerEnabled],["Capital budget",c.budget>0],["Per-order cap",c.maxOrder>0&&c.maxOrder<=c.budget*s.livePositionPct],["Daily buy cap",c.maxDaily>0],["Daily loss cap",c.maxLoss>0],["Approval artifact hash",/^[a-f0-9]{64}$/.test(c.approvalHash)],["Dedicated RPC",!c.rpc.includes("api.mainnet-beta.solana.com")],["Jupiter credentials",!!c.jupiterKey],["Signer authentication",c.signerToken.length>=32],["Reviewed asset policy",!s.requireAssetReview||validAssetPolicy(assetPolicy).length>0]]}
