import { inspect } from './intelligence.mjs';
import { strategy } from './strategy.mjs';

const ENGINE_VERSION='multi-engine-v4';
const SHADOW_ONLY=true;
const OUTCOME_HORIZONS=[60000,300000,900000,3600000];
const PROMOTION={minSamples:30,minWinRate:0.55,minMeanReturn:0.005,minLower95:0,minRiskAdjusted:0.15};
const unique=a=>[...new Set(a)];
const mean=a=>a.length?a.reduce((n,x)=>n+x,0)/a.length:0;
const std=a=>{if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((n,x)=>n+(x-m)**2,0)/(a.length-1))};
const keyFor=s=>unique((s.engines??[]).map(e=>e.engine)).sort().join('+');
function metrics(r){const samples=r.length,m=mean(r),sd=std(r),winRate=samples?r.filter(x=>x>0).length/samples:0,se=samples?sd/Math.sqrt(samples):0,lower95=m-1.96*se,riskAdjusted=sd?m/sd:m>0?m:0;return{samples,meanReturn:m,winRate,volatility:sd,lower95,riskAdjusted}}
function promotion(m){const checks={minSamples:m.samples>=PROMOTION.minSamples,minWinRate:m.winRate>=PROMOTION.minWinRate,minMeanReturn:m.meanReturn>=PROMOTION.minMeanReturn,positiveLower95:m.lower95>PROMOTION.minLower95,minRiskAdjusted:m.riskAdjusted>=PROMOTION.minRiskAdjusted};return{eligible:Object.values(checks).every(Boolean),checks,thresholds:PROMOTION}}
async function pairPrice(ctx,mint){const pair=(await ctx.p.pairs(mint))[0],price=Number(pair?.priceUsd),liquidity=Number(pair?.liquidity?.usd??pair?.liquidityUsd??0);return Number.isFinite(price)&&price>0?{price,liquidity}:null}
async function settleOutcomes(ctx,now){const signals=ctx.s.entities('engine_signal',500).filter(x=>x.entryPrice>0&&Array.isArray(x.engines));for(const s of signals){const outcomes={...(s.outcomes??{})},due=OUTCOME_HORIZONS.filter(h=>outcomes[h]==null&&now-s.at>=h);if(!due.length)continue;let q;try{q=await pairPrice(ctx,s.mint)}catch{continue}if(!q)continue;for(const h of due){const ret=q.price/s.entryPrice-1;outcomes[h]={at:now,price:q.price,return:ret,win:ret>0};ctx.s.event('ENGINE_SIGNAL_OUTCOME',{signalId:s.id,mint:s.mint,horizonMs:h,entryPrice:s.entryPrice,price:q.price,return:ret,engines:s.engines.map(e=>e.engine),combination:keyFor(s),policy:s.policy})}ctx.s.entity('engine_signal',s.id,{...s,outcomes,updatedAt:now})}const settled=ctx.s.entities('engine_signal',1000),rows=[],names=unique(settled.flatMap(s=>(s.engines??[]).map(e=>e.engine))),combos=unique(settled.map(keyFor).filter(Boolean));for(const h of OUTCOME_HORIZONS){for(const name of names){const r=settled.filter(s=>(s.engines??[]).some(e=>e.engine===name)&&s.outcomes?.[h]).map(s=>Number(s.outcomes[h].return)).filter(Number.isFinite);if(r.length){const m=metrics(r);rows.push({type:'engine',name,horizonMs:h,...m,promotion:promotion(m),updatedAt:now})}}for(const name of combos){const r=settled.filter(s=>keyFor(s)===name&&s.outcomes?.[h]).map(s=>Number(s.outcomes[h].return)).filter(Number.isFinite);if(r.length){const m=metrics(r);rows.push({type:'combination',name,horizonMs:h,...m,promotion:promotion(m),updatedAt:now})}}}ctx.s.entity('experiment','engine-leaderboard',{at:now,policy:ENGINE_VERSION,shadowOnly:SHADOW_ONLY,promotionPolicy:PROMOTION,eligible:rows.filter(r=>r.promotion.eligible),rows:rows.sort((a,b)=>b.lower95-a.lower95)})}

export function installMultiEngine(Trader){if(Trader.prototype.__multiEngineInstalled)return;Trader.prototype.__multiEngineInstalled=true;const original=Trader.prototype.evaluate;Trader.prototype.evaluate=async function(){await original.call(this);if(this.s.get('paused',false))return;const st=strategy(),now=Date.now(),maxAge=this.c.mode==='live'?st.maxDataAgeMsLive:st.maxDataAgeMsPaper;if(now-this.s.get('lastBlockTime',0)>maxAge)return;try{await settleOutcomes(this,now)}catch{}
const recent=this.s.db.prepare('SELECT body FROM observations WHERE at>=? ORDER BY at').all(now-Math.max(st.observationWindowMs,900000)).map(r=>JSON.parse(r.body)),candidateMints=unique(recent.filter(x=>x.side==='buy'&&x.mint).map(x=>x.mint)).slice(-st.signalMintLimit);
for(const mint of candidateMints){const fifteen=recent.filter(x=>x.mint===mint),five=fifteen.filter(x=>x.at>=now-300000),two=fifteen.filter(x=>x.at>=now-120000),one=fifteen.filter(x=>x.at>=now-60000),prior=five.filter(x=>x.at<now-60000),buys=five.filter(x=>x.side==='buy'),sells=five.filter(x=>x.side==='sell'),buyers=unique(buys.map(x=>x.wallet).filter(Boolean)),sellers=unique(sells.map(x=>x.wallet).filter(Boolean)),engines=[],flowRatio=buys.length/Math.max(1,buys.length+sells.length);
if(buyers.length>=3&&buys.length>=4&&flowRatio>=0.75)engines.push({engine:'breadth',score:Math.min(100,45+buyers.length*8+flowRatio*20),evidence:{buyers:buyers.length,buys:buys.length,sells:sells.length,buyRatio:flowRatio}});
const currentRate=one.filter(x=>x.side==='buy').length,priorRate=prior.filter(x=>x.side==='buy').length/4;if(currentRate>=3&&currentRate>=Math.max(2,priorRate*2))engines.push({engine:'flow_acceleration',score:Math.min(100,50+currentRate*8),evidence:{buysLastMinute:currentRate,priorBuysPerMinute:priorRate}});
const netWallets=buyers.filter(w=>!sellers.includes(w)).length;if(buyers.length>=4&&netWallets>=3&&sellers.length<=Math.max(1,Math.floor(buyers.length/3)))engines.push({engine:'accumulation',score:Math.min(100,50+netWallets*7+(buyers.length-sellers.length)*3),evidence:{buyers:buyers.length,sellers:sellers.length,netAccumulatingWallets:netWallets}});
const recentBuys=two.filter(x=>x.side==='buy'),earlyBuys=fifteen.filter(x=>x.side==='buy'&&x.at<now-120000);if(recentBuys.length>=4&&unique(recentBuys.map(x=>x.wallet)).length>=3&&earlyBuys.length<=Math.max(2,recentBuys.length/2))engines.push({engine:'new_attention',score:Math.min(100,50+recentBuys.length*5),evidence:{recentBuys:recentBuys.length,priorBuys:earlyBuys.length,recentBuyers:unique(recentBuys.map(x=>x.wallet)).length}});
const recentSells=two.filter(x=>x.side==='sell').length,olderSells=fifteen.filter(x=>x.side==='sell'&&x.at<now-120000).length;if(recentBuys.length>=3&&recentSells===0&&olderSells>=2)engines.push({engine:'sell_exhaustion',score:Math.min(100,55+recentBuys.length*5),evidence:{recentBuys:recentBuys.length,recentSells,olderSells}});
let quote;try{quote=await pairPrice(this,mint);const snap=this.s.get('engine:price:'+mint,null);if(quote){if(snap&&Number.isFinite(snap.price)&&snap.price>0&&now-snap.at>=30000&&now-snap.at<=900000){const change=quote.price/snap.price-1;if(change>=0.02&&change<=0.25)engines.push({engine:'price_momentum',score:Math.min(100,50+change*200),evidence:{change,from:snap.price,to:quote.price,ageMs:now-snap.at,liquidityUsd:quote.liquidity}});if(change>=-0.03&&change<=0.015&&buyers.length>=3&&flowRatio>=0.7)engines.push({engine:'compression_accumulation',score:Math.min(100,55+buyers.length*5),evidence:{change,buyers:buyers.length,buyRatio:flowRatio,liquidityUsd:quote.liquidity}})}if(!snap||now-snap.at>=60000)this.s.set('engine:price:'+mint,{at:now,price:quote.price})}}catch{}
if(!engines.length)continue;let risk;try{risk=await inspect(mint,this.p,this.c)}catch(e){risk={score:0,reasons:['Risk inspection failed: '+String(e?.message??e)]}}const reasons=[...(risk.reasons??[])];if(engines.length<2)reasons.push('Multi-engine consensus requires 2 independent engines');if(st.requireRouterCredentials&&!this.c.jupiterKey)reasons.push('Router credentials missing');const score=Math.round(engines.reduce((n,e)=>n+e.score,0)/engines.length*(1-st.signalRiskWeight)+Number(risk.score??0)*st.signalRiskWeight),id='engine:'+mint+':'+Math.floor(now/st.signalBucketMs);if(this.s.get(id))continue;const signal={id,mint,symbol:risk.symbol,at:now,score,action:reasons.length?'REJECT':'SHADOW_BUY',reasons,policy:ENGINE_VERSION,entryPrice:quote?.price??null,engines,evidence:{engines,risk,strategy:st,shadowOnly:SHADOW_ONLY}};this.s.tx(()=>{this.s.entity('signal',id,signal);this.s.entity('engine_signal',id,{...signal,outcomes:{}});this.s.event(reasons.length?'ENGINE_SIGNAL_REJECTED':'ENGINE_SIGNAL_SHADOW',signal,id);this.s.set(id,true)})}}}
