import {createServer} from 'node:http';

const port=Number(process.env.PORT||8080);let status={alive:true,service:'astratrader',warming:true,ready:false,bootError:null};
const clean=(message)=>String(message??'Runtime initialization failed').replace(/https?:\/\/\S+/g,'[url]').slice(0,300);
const listenPort=Number.isInteger(port)&&port>0&&port<65536?port:8080;
const bootstrap=createServer((req,res)=>{if(req.url==='/healthz'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});return res.end(JSON.stringify(status))}if(req.url==='/webhooks/solana'||req.url==='/mcp'){res.writeHead(503,{'content-type':'application/json','cache-control':'no-store'});return res.end(JSON.stringify({error:'AstraTrader warming up'}))}res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(`<!doctype html><html><meta charset="utf-8"><title>AstraTrader startup</title><body style="font:16px system-ui;background:#0b1014;color:#e1e9ee;padding:40px"><h1>AstraTrader startup</h1><pre>${JSON.stringify(status,null,2).replaceAll('<','&lt;')}</pre></body></html>`)});
bootstrap.listen(listenPort,'0.0.0.0',async()=>{console.log(JSON.stringify({event:'bootstrap_started'}));try{const [{config,assets,validAssetPolicy},{Store},{SupabasePersistence},{Trader},{createApp},{handleMcp}]=await Promise.all([import('./config.mjs'),import('./db.mjs'),import('./supabase.mjs'),import('./trader.mjs'),import('./server-agent.mjs'),import('./mcp.mjs')]);const c=config();if(c.apiToken.length<32)throw Error('ADMIN_TOKEN must be at least 32 characters');if(process.env.PERSISTENCE_CONFIRMED!=='true')throw Error('PERSISTENCE_CONFIRMED must be true');const persistence=c.persistence==='supabase'?new SupabasePersistence(c.supabaseURL,c.supabaseKey):null;const store=new Store(c.persistence==='supabase'?':memory:':c.db,persistence);if(persistence)await persistence.hydrate(store);const persistedPolicy=store.get('assetPolicy',null);c.runtimeAssets=persistedPolicy===null?assets(c):validAssetPolicy(persistedPolicy);if(persistedPolicy===null){store.set('assetPolicy',c.runtimeAssets);await store.flush()}const trader=new Trader(c,store);status={...status,warming:false,ready:true};console.log(JSON.stringify({event:'runtime_preflight_ok'}));bootstrap.close(()=>{const server=createApp(c,store,trader),baseHandler=server.listeners('request')[0];server.removeAllListeners('request');server.on('request',async(req,res)=>{try{if(await handleMcp(req,res,c))return;return baseHandler(req,res)}catch(e){if(!res.headersSent)res.writeHead(500,{'content-type':'application/json'});if(!res.writableEnded)res.end(JSON.stringify({error:clean(e?.message??e)}))}});server.requestTimeout=20000;server.headersTimeout=10000;server.listen(listenPort,'0.0.0.0',()=>console.log(JSON.stringify({event:'trader_started',port:listenPort,mode:c.mode,persistence:c.persistence,agentApi:'v1',mcp:'2026-07-28'})));let timer;async function loop(){if(trader.stop)return;await trader.cycle();await store.flush();timer=setTimeout(loop,c.pollMs)}void loop();let closing=false;async function shutdown(){if(closing)return;closing=true;trader.stop=true;clearTimeout(timer);server.close();const poll=setInterval(async()=>{if(!trader.busy){clearInterval(poll);try{await store.flush()}finally{store.close();process.exit(0)}}},100);setTimeout(()=>process.exit(1),30000).unref()}process.removeAllListeners('SIGTERM');process.removeAllListeners('SIGINT');process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown)})}catch(e){status={...status,warming:false,ready:false,bootError:clean(e?.message??e)};console.error(JSON.stringify({event:'runtime_preflight_failed',message:status.bootError}))}});
process.on('SIGTERM',()=>bootstrap.close(()=>process.exit(0)));
process.on('SIGINT',()=>bootstrap.close(()=>process.exit(0)));
