const TABLES = {
  meta: "astratrader_meta", events: "astratrader_events", jobs: "astratrader_jobs", observations: "astratrader_observations", orders: "astratrader_orders", entities: "astratrader_entities", reservations: "astratrader_reservations",
};
const ACTIVE_JOB_MAX_AGE_MS=60000, READ_TIMEOUT_MS=60000;
const TERMINAL_JOB_STATES=new Set(["done","dead"]);
const HOUR=3600000, DAY=24*HOUR;
const RETENTION={events:3*DAY,observations:7*DAY,signal:6*HOUR,engine_signal:30*DAY,temporal_engine_signal:30*DAY,token:7*DAY,health:DAY};
const PRUNE_INTERVAL_MS=15*60*1000;
const STARTUP_PRUNE_DELAY_MS=120000;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const transientHydrationError=error=>/statement timeout|57014|HTTP 5\d\d|transport unavailable|timeout|aborted/i.test(String(error?.message??error??""));
export class SupabasePersistence {
 constructor(url,key,fetcher=fetch){this.base=new URL("/rest/v1/",url);this.key=key;this.fetcher=fetcher;this.lastPruneAt=0;this.prunePromise=null;this.startupPruneScheduled=false}
 headers(extra={}){return{apikey:this.key,authorization:`Bearer ${this.key}`,"content-type":"application/json",...extra}}
 async request(path,options={}){const method=options.method??"GET",retryable=method==="GET";let lastError;for(let attempt=0;attempt<(retryable?3:1);attempt++){try{const response=await this.fetcher(new URL(path,this.base),{...options,method,headers:this.headers(options.headers),signal:AbortSignal.timeout(retryable?READ_TIMEOUT_MS:15000),redirect:"error"});if(response.status===416&&method==="GET")return[];if(!response.ok){const text=await response.text().catch(()=>"");const error=Error(`Supabase persistence HTTP ${response.status}${text?`: ${text.slice(0,240)}`:""}`);if(retryable&&transientHydrationError(error)&&attempt<2){lastError=error;await sleep(500*2**attempt);continue}throw error}if(response.status===204)return null;const text=await response.text();return text?JSON.parse(text):null}catch(error){lastError=error;if(!retryable||!transientHydrationError(error)||attempt===2)throw error;await sleep(500*2**attempt)}}throw lastError}
 async rows(table,{select="*",order="",filters={},maxRows=10000,pageSize=1000}={}){const out=[],size=Math.max(1,Math.min(1000,pageSize));for(let offset=0;offset<maxRows;offset+=size){const params=new URLSearchParams({select});if(order)params.set("order",order);for(const[k,v]of Object.entries(filters))params.set(k,v);const wanted=Math.min(size,maxRows-offset),page=await this.request(`${TABLES[table]}?${params}`,{headers:{Range:`${offset}-${offset+wanted-1}`}});if(!Array.isArray(page))throw Error(`Unexpected Supabase ${table} response`);out.push(...page);if(page.length<wanted)break}return out}
 async observationRows({maxRows=100000,pageSize=500}={}){const out=[],size=Math.max(1,Math.min(1000,pageSize));let cursor=null;while(out.length<maxRows){const wanted=Math.min(size,maxRows-out.length),params=new URLSearchParams({select:"*",order:"at.desc,id.desc",limit:String(wanted)});if(cursor)params.set("or",`(at.lt.${cursor.at},and(at.eq.${cursor.at},id.lt.${cursor.id}))`);const page=await this.request(`${TABLES.observations}?${params}`);if(!Array.isArray(page))throw Error("Unexpected Supabase observations response");out.push(...page);if(page.length<wanted)break;const last=page.at(-1);if(!last||last.at==null||!last.id)break;cursor={at:last.at,id:last.id}}return out}
 async eventRows({maxRows=10000,pageSize=500}={}){const out=[],size=Math.max(1,Math.min(1000,pageSize));let beforeSeq=null;while(out.length<maxRows){const wanted=Math.min(size,maxRows-out.length),params=new URLSearchParams({select:"*",order:"seq.desc",limit:String(wanted)});if(beforeSeq!==null)params.set("seq",`lt.${beforeSeq}`);const page=await this.request(`${TABLES.events}?${params}`);if(!Array.isArray(page))throw Error("Unexpected Supabase events response");out.push(...page);if(page.length<wanted)break;const last=page.at(-1);if(last?.seq==null)break;beforeSeq=last.seq}return out}
 async entityRows(kind,{maxRows=10000,pageSize=500}={}){const out=[],size=Math.max(1,Math.min(1000,pageSize));let cursor=null;while(out.length<maxRows){const wanted=Math.min(size,maxRows-out.length),params=new URLSearchParams({select:"*",kind:`eq.${kind}`,order:"at.desc,id.desc",limit:String(wanted)});if(cursor)params.set("or",`(at.lt.${cursor.at},and(at.eq.${cursor.at},id.lt.${cursor.id}))`);const page=await this.request(`${TABLES.entities}?${params}`);if(!Array.isArray(page))throw Error(`Unexpected Supabase ${kind} entities response`);out.push(...page);if(page.length<wanted)break;const last=page.at(-1);if(!last||last.at==null||!last.id)break;cursor={at:last.at,id:last.id}}return out}
 async deleteWhere(table,filters){const params=new URLSearchParams(filters);await this.request(`${TABLES[table]}?${params}`,{method:"DELETE",headers:{Prefer:"return=minimal"}})}
 async deleteJobs(filters){return this.deleteWhere("jobs",filters)}
 async pruneJobs(now=Date.now()){const cutoff=now-ACTIVE_JOB_MAX_AGE_MS;await Promise.all([this.deleteJobs({state:"in.(done,dead)"}),this.deleteJobs({state:"eq.pending",available:`lt.${cutoff}`}),this.deleteJobs({state:"eq.running",lease_until:`lt.${now}`})])}
 async pruneRetention(now=Date.now(),force=false){if(!force&&now-this.lastPruneAt<PRUNE_INTERVAL_MS)return;if(this.prunePromise)return this.prunePromise;this.lastPruneAt=now;this.prunePromise=(async()=>{await this.pruneJobs(now);await this.deleteWhere("observations",{at:`lt.${now-RETENTION.observations}`});await this.deleteWhere("events",{at:`lt.${now-RETENTION.events}`});for(const kind of ["signal","engine_signal","temporal_engine_signal","token","health"]){await this.deleteWhere("entities",{kind:`eq.${kind}`,at:`lt.${now-RETENTION[kind]}`})}})().finally(()=>{this.prunePromise=null});return this.prunePromise}
 scheduleStartupPrune(){if(this.startupPruneScheduled)return;this.startupPruneScheduled=true;const timer=setTimeout(()=>{this.pruneRetention(Date.now(),true).catch(()=>{}).finally(()=>{this.startupPruneScheduled=false})},STARTUP_PRUNE_DELAY_MS);timer.unref?.()}
 async upsert(table,row,conflict){if(table==="jobs"&&!Array.isArray(row)&&TERMINAL_JOB_STATES.has(row?.state)){await this.deleteJobs({id:`eq.${row.id}`});return}const suffix=conflict?`?on_conflict=${encodeURIComponent(conflict)}`:"";await this.request(TABLES[table]+suffix,{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(row)});if(table!=="jobs")void this.pruneRetention().catch(()=>{})}
 async insertEvent(row){for(let attempt=0;attempt<8;attempt++){const latestQuery=new URLSearchParams({select:"seq",order:"seq.desc",limit:"1"}),latest=await this.request(`${TABLES.events}?${latestQuery}`),seq=Number(latest?.[0]?.seq??0)+1,insertQuery=new URLSearchParams({select:"seq"});const response=await this.fetcher(new URL(`${TABLES.events}?${insertQuery}`,this.base),{method:"POST",headers:this.headers({Prefer:"return=representation"}),body:JSON.stringify({seq,id:row.id,at:row.at,kind:row.kind,body:row.body,prev:row.prev,hash:row.hash}),signal:AbortSignal.timeout(15000),redirect:"error"});if(response.ok){const text=await response.text(),created=text?JSON.parse(text):null;if(!Array.isArray(created)||Number(created[0]?.seq)!==seq)throw Error("Unexpected Supabase event insert response");void this.pruneRetention().catch(()=>{});return seq}const text=await response.text().catch(()=>"");if(response.status!==409)throw Error(`Supabase persistence HTTP ${response.status}${text?`: ${text.slice(0,240)}`:""}`);const existingQuery=new URLSearchParams({select:"seq",id:`eq.${row.id}`,limit:"1"}),existing=await this.request(`${TABLES.events}?${existingQuery}`);if(existing?.[0]?.seq!=null)return Number(existing[0].seq)}throw Error("Supabase event sequence allocation contention")}
 async hydrateOnce(store){const now=Date.now(),cutoff=now-ACTIVE_JOB_MAX_AGE_MS;const[meta,jobs,orders,reservations]=await Promise.all([this.rows("meta",{order:"key.asc",maxRows:2000}),this.rows("jobs",{order:"available.desc",filters:{state:"in.(pending,running)",available:`gte.${cutoff}`},maxRows:5000,pageSize:500}),this.rows("orders",{order:"updated.desc",maxRows:20000,pageSize:500}),this.rows("reservations",{order:"day.desc,id.desc",maxRows:2000,pageSize:500})]);const eventsDesc=await this.eventRows({maxRows:10000,pageSize:500}),observationsDesc=await this.observationRows({maxRows:100000,pageSize:500}),walletEntities=await this.entityRows("wallet",{maxRows:40000,pageSize:500}),edgeEntities=await this.entityRows("edge",{maxRows:30000,pageSize:500}),signalEntities=await this.entityRows("signal",{maxRows:2000,pageSize:250}),engineSignalEntities=await this.entityRows("engine_signal",{maxRows:10000,pageSize:500}),temporalEngineSignalEntities=await this.entityRows("temporal_engine_signal",{maxRows:10000,pageSize:500}),tokenEntities=await this.entityRows("token",{maxRows:2000,pageSize:250}),smallKinds=["signer","health","liveEquity","experiment"],smallEntities=(await Promise.all(smallKinds.map(kind=>this.entityRows(kind,{maxRows:100,pageSize:100})))).flat(),entities=[...walletEntities,...edgeEntities,...signalEntities,...engineSignalEntities,...temporalEngineSignalEntities,...tokenEntities,...smallEntities];store.hydrate({meta,events:eventsDesc.reverse(),jobs,observations:observationsDesc.reverse(),orders,entities,reservations});this.scheduleStartupPrune()}
 async hydrate(store){let lastError;for(let attempt=0;attempt<2;attempt++){try{return await this.hydrateOnce(store)}catch(error){lastError=error;if(!transientHydrationError(error)||attempt===1)throw error;await sleep(1000)}}throw lastError}
}
