'use client';
import {useEffect,useState} from 'react';
const money=(n:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n||0));
const pct=(n:any)=>`${(Number(n||0)*100).toFixed(1)}%`;
const age=(ms:any)=>ms==null?'unknown':Number(ms)<1000?`${ms}ms`:`${(Number(ms)/1000).toFixed(1)}s`;
const short=(s:any)=>s?`${String(s).slice(0,5)}…${String(s).slice(-5)}`:'—';
const arr=(v:any)=>Array.isArray(v)?v:[];
const num=(...v:any[])=>{for(const x of v)if(x!==undefined&&x!==null&&Number.isFinite(Number(x)))return Number(x);return 0};
export default function Home(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/state',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error||'State unavailable');setData(j);setError('')}catch(e:any){setError(e.message||String(e))}}
 async function refresh(){setBusy(true);try{const r=await fetch('/api/tick',{method:'POST'}),j=await r.json();if(!r.ok||j.ok===false)throw Error(j.error||'Refresh unavailable');await load()}catch(e:any){setError(e.message||String(e))}finally{setBusy(false)}}
 useEffect(()=>{load();const p=setInterval(load,10000);return()=>clearInterval(p)},[]);
 const s=data?.state||{},strategy=data?.strategy||data?.policy||{},wallets=arr(data?.wallets),positions=arr(s.positions),opps=arr(data?.opportunities?.opportunities||data?.opportunities||data?.signals);
 const eligible=wallets.filter((w:any)=>w.eligible),freshMs=num(data?.finalizedDataAgeMs,s.finalizedDataAgeMs,s.dataAgeMs),freshLimit=num(strategy.maxDataAgeMsLive,strategy.freshnessMaxMs,strategy.maxDataAgeMs,20000);
 const correlation=num(strategy.correlationGroupsRequired,strategy.independentGroupsRequired,2),walletMin=num(strategy.walletMinRoundTrips,strategy.minimumRoundTrips,6),walletScore=num(strategy.walletMinScore,strategy.minimumWalletScore,50);
 const posPct=num(strategy.livePositionPct,strategy.positionFraction,.02),exposure=num(strategy.portfolioExposureLimitPct,strategy.portfolioExposureFraction,.15),drawdown=num(strategy.liveMaxDrawdownPct,strategy.maxDrawdownFraction,.10),stop=num(strategy.liveStopLossPct,strategy.stopLossFraction,.10),target=num(strategy.liveTakeProfitPct,strategy.takeProfitFraction,.20),maxHold=num(strategy.liveMaxHoldMs,strategy.maxHoldMs,3600000);
 const equity=num(s.equity,s.effectiveBankrollUsdc,s.cash);const blockers=new Map<string,number>();opps.forEach((o:any)=>arr(o.reasons||o.blockers||o.rejectReasons).forEach((r:any)=>blockers.set(String(r),(blockers.get(String(r))||0)+1)));const topBlockers=[...blockers.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6);
 const status=s.haltReason?'HALTED':s.running===false?'PAUSED':freshMs>freshLimit?'DATA STALE':'WATCHING';
 return <><header><div className="brand"><b>◈</b> ASTRATRADER <small className="muted" style={{letterSpacing:'.04em',marginLeft:16}}>LIVE INTELLIGENCE</small></div><div className="actions"><span className="tag">SOLANA / MAINNET</span><span className="tag">{status}</span></div></header><main>
 <div className="topline"><div><div className="muted mono" style={{fontSize:12,letterSpacing:'.15em',marginBottom:8}}>HUMAN-READABLE AGENT STATE</div><h1>What Astra is seeing right now.</h1><p className="muted">Live strategy, evidence, blockers and execution readiness.</p></div><button className="btn primary" disabled={busy} onClick={refresh}>{busy?'Refreshing…':'Refresh intelligence'}</button></div>
 {error&&<div className="notice">{error}</div>}{s.haltReason&&<div className="notice">Trading halted: {s.haltReason}</div>}
 <section className="panel"><div className="split"><h2>What Astra is waiting for</h2><span className="tag">{status}</span></div><p style={{fontSize:20,lineHeight:1.5,margin:'12px 0'}}>Waiting for {correlation} independent qualified wallet groups to converge on the same acceptable token while finalized market data is fresh enough to trade.</p><p className="muted">A token being safe is not enough. A wallet being profitable is not enough. Wallet evidence, independent confirmation, token safety, market quality and execution checks must all agree.</p></section>
 <div className="stats"><div className="stat"><label>Effective bankroll</label><strong>{money(equity)}</strong><small className="muted">Realized P&amp;L {money(s.realized)}</small></div><div className="stat"><label>Open positions</label><strong>{positions.length}</strong><small className="muted">Only qualified entries appear here</small></div><div className="stat"><label>Wallet intelligence</label><strong>{wallets.length}</strong><small className="muted">{eligible.length} currently eligible</small></div><div className="stat"><label>Finalized data age</label><strong className={freshMs>freshLimit?'bad':'good'}>{age(freshMs)}</strong><small className="muted">Live maximum {age(freshLimit)}</small></div></div>
 <div className="grid"><section className="panel"><h2>Current strategy</h2>{[
 ['Wallet qualification',`At least ${walletMin} completed round trips, score ≥ ${walletScore}, positive conservative expectancy, and no active taint.`],
 ['Independent confirmation',`${correlation} independent eligible wallet groups must converge on the same token.`],
 ['Market freshness',`Finalized evidence must be no older than ${age(freshLimit)} at decision time.`],
 ['Position sizing',`Target entry size is ${pct(posPct)} of effective bankroll.`],
 ['Portfolio exposure',`Maximum portfolio exposure is ${pct(exposure)}.`],
 ['Exit plan',`${pct(stop)} stop loss, ${pct(target)} take profit, or ${Math.round(maxHold/60000)} minute maximum hold.`],
 ['Capital protection',`New risk stops at ${pct(drawdown)} drawdown from peak.`]
 ].map(([k,v])=><div className="listrow" key={k}><b>{k}</b><p className="muted" style={{marginTop:5}}>{v}</p></div>)}</section>
 <section className="panel"><h2>Why Astra is not trading</h2>{topBlockers.length?topBlockers.map(([r,c])=><div className="split listrow" key={r}><span>{r}</span><span className="tag">{c} candidate{c===1?'':'s'}</span></div>):<div className="empty">No candidate rejection reasons are currently exposed by the state feed.</div>}<p className="muted" style={{marginTop:18}}>Passing on a candidate is normal. Astra waits until every required gate aligns instead of forcing activity.</p></section></div>
 <div className="grid"><section className="panel"><h2>Qualified wallets</h2>{eligible.length?eligible.slice(0,12).map((w:any)=><div className="listrow split" key={w.wallet}><div><b className="mono">{short(w.wallet)}</b><p className="muted">{num(w.roundTrips,w.round_trips)} round trips · score {num(w.score)}</p></div><span className="good">ELIGIBLE</span></div>):<div className="empty">No wallet currently meets the evidence threshold.</div>}</section>
 <section className="panel"><h2>Execution readiness</h2>{[['Agent',s.running===false?'Paused':'Running'],['Finalized data',freshMs<=freshLimit?'Fresh enough':`Stale — ${age(freshMs)} old`],['Kill switch',s.haltReason?'BLOCKED':'Clear'],['Open positions',String(positions.length)],['Processing lag',age(data?.processingLagMs??s.processingLagMs)],['Provider',s.provider||'Connected']].map(([k,v])=><div className="split listrow" key={k}><span className="muted">{k}</span><span>{v}</span></div>)}</section></div>
 <section className="panel"><div className="split"><h2>Recent candidates</h2><span className="muted">{opps.length} visible</span></div>{opps.length?opps.slice(0,20).map((o:any,i:number)=>{const reasons=arr(o.reasons||o.blockers||o.rejectReasons),ok=o.eligible||o.action==='BUY'||o.action==='ACCEPT';return <div className="listrow" key={o.id||o.mint||i}><div className="split"><b>{o.symbol||short(o.mint)}</b><span className={ok?'good':'bad'}>{ok?'ACTIONABLE':'PASS'}</span></div><p className="muted" style={{marginTop:6}}>{reasons.length?reasons.join(' · '):ok?'All exposed gates passed.':'No detailed rejection reason exposed.'}</p></div>}):<div className="empty">No current candidates. Astra is watching wallet and market evidence.</div>}</section>
 <section className="panel"><h2>Open live positions</h2>{positions.length?positions.map((p:any)=><div className="split listrow" key={p.mint}><span>{p.symbol||short(p.mint)}</span><span>{money(p.value??p.qty*p.mark)}</span></div>):<div className="empty">No open positions. Astra has not found a fully qualified live entry.</div>}</section>
 <footer className="split"><span>ASTRATRADER · live API translated for humans</span><span>No synthetic activity · no forced trades</span></footer></main></>;
}
