'use client';
import {useEffect,useState,useRef} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Activity,ArrowUpRight,ShieldCheck,Network,Radio,Download,RefreshCw} from 'lucide-react';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n??0);
const short=(s:string)=>s?`${s.slice(0,5)}…${s.slice(-5)}`:'—';
const time=(n:number)=>n?new Date(n).toLocaleTimeString():'—';
const pct=(n:number|null)=>n==null?'—':`${(n*100).toFixed(1)}%`;
export default function Home(){const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<any>(null),[search,setSearch]=useState(''),[tab,setTab]=useState('overview');const cycling=useRef(false);
 async function load(){try{const r=await fetch('/api/state');const j=await r.json();if(!r.ok)throw Error(j.error);setData(j)}catch(e){setError(String(e))}}
 async function tick(){if(cycling.current)return;cycling.current=true;setBusy(true);try{const r=await fetch('/api/tick',{method:'POST'});const j=await r.json();if(!r.ok||j.ok===false)throw Error(j.error||'Collection unavailable');setError('')}catch(e){setError(String(e))}finally{cycling.current=false;setBusy(false);await load()}}
 useEffect(()=>{load();const p=setInterval(load,10000);return()=>clearInterval(p)},[]);
 useEffect(()=>{if(!data?.state.running)return;const p=setInterval(tick,30000);return()=>clearInterval(p)},[data?.state.running]);
 async function action(action:string){setBusy(true);try{const r=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const j=await r.json();if(!r.ok)throw Error(j.error);setError('');await load()}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function replay(){setBusy(true);try{const r=await fetch('/api/backtest',{method:'POST'});if(!r.ok)throw Error('Replay failed');setSelected({title:'Replay report',...await r.json()});await load()}catch(e){setError(String(e))}finally{setBusy(false)}}
 const s=data?.state;const equity=s?s.cash+s.positions.reduce((n:number,p:any)=>n+p.qty*p.mark,0):1000;const series=data?.equity??[];const lo=Math.min(1000,...series.map((p:any)=>p.equity))*0.995,hi=Math.max(1000,...series.map((p:any)=>p.equity))*1.005;const points=series.map((p:any,i:number)=>`${40+i/Math.max(1,series.length-1)*700},${150-(p.equity-lo)/(hi-lo)*120}`).join(' ');
 const empty=(text:string)=><div className="empty">{text}</div>;const events=(data?.events??[]).filter((e:any)=>JSON.stringify(e).toLowerCase().includes(search.toLowerCase()));
 return <><header><div className="brand"><b>◈</b> ACTOR <small className="muted" style={{letterSpacing:'.04em',marginLeft:16}}>INTELLIGENCE TERMINAL</small></div><div className="actions"><span className="tag">SOLANA / MAINNET</span><span className="tag">PAPER ONLY</span></div></header><main><div className="topline"><div><div className="muted mono" style={{fontSize:12,letterSpacing:'.15em',marginBottom:8}}>RESEARCH SESSION / 001</div><h1>Follow the evidence.</h1><p className="muted">Wallet behavior. Independent signals. Accountable decisions.</p></div><div className="actions"><button className="btn" disabled={busy} onClick={()=>action(s?.running?'pause':'resume')}>{s?.running?'Pause collection':'Resume collection'}</button><button className="btn primary" disabled={busy} onClick={tick}><RefreshCw size={14} style={{display:'inline',marginRight:8}}/>{busy?'Working…':'Collect next block'}</button><button className="btn danger" disabled={busy||!!s?.haltReason} onClick={()=>action('kill')}>Kill switch</button></div></div>
 {error&&<div role="alert" className="notice">{error}</div>}{s?.haltReason&&<div className="notice">New entries blocked: {s.haltReason}. Existing positions remain visible.</div>}
 <div className="notice">Observed-window research · Collection runs every 30 seconds while this terminal is open. Unattended collection requires the included collector runner. Unknown risk factors block entries.</div>
 <div className="stats"><div className="stat"><label>Paper equity</label><strong>{money(equity)}</strong><small className="muted">Starting balance {money(1000)}</small></div><div className="stat"><label>Realized P&amp;L</label><strong className={s?.realized<0?'bad':'good'}>{money(s?.realized??0)}</strong><small className="muted">{data?.statistics.closed??0} closed paper positions</small></div><div className="stat"><label>Discovered wallets</label><strong>{data?.wallets.length??0}</strong><small className="muted">{data?.wallets.filter((w:any)=>w.eligible).length??0} meet evidence threshold</small></div><div className="stat"><label>Finalized blocks collected</label><strong>{s?.blocks??0}</strong><small className="muted">{s?.transactions?.toLocaleString()??0} transactions inspected</small></div></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="tabsbar">{['overview','signals','wallets','tokens','graph','decisions','experiments'].map(t=><TabsTrigger key={t} value={t}>{t.charAt(0).toUpperCase()+t.slice(1)}</TabsTrigger>)}</TabsList>
 <TabsContent value="overview"><div className="grid"><section className="panel"><div className="split"><h2>Equity curve <small className="muted"> / USD</small></h2><span className="tag">OBSERVED PAPER ACCOUNT</span></div>{series.length?<svg className="chart" viewBox="0 0 800 190" role="img" aria-label="Paper equity over collected observations">{[35,85,135].map(y=><line key={y} x1="40" x2="740" y1={y} y2={y} stroke="#293740" strokeDasharray="4 6"/>)}<polyline points={points} fill="none" stroke="#a4eead" strokeWidth="2"/><text x="40" y="180">{time(series[0]?.at)}</text><text x="640" y="180">{time(series.at(-1)?.at)}</text><text x="44" y="20">{money(equity)}</text></svg>:empty('No equity observations yet. Collect a block to begin recording.')}<div className="metrics"><div><span className="muted">Cash</span><p className="mono">{money(s?.cash??1000)}</p></div><div><span className="muted">Unrealized</span><p className="mono">{money(s?.positions.reduce((n:number,p:any)=>n+p.qty*p.mark-p.cost,0)??0)}</p></div><div><span className="muted">Drawdown</span><p className="mono">{pct(s?(s.peak-equity)/s.peak:0)}</p></div><div><span className="muted">Exposure</span><p className="mono">{pct((equity-(s?.cash??1000))/equity)}</p></div></div></section><section className="panel"><h2><ShieldCheck size={17} style={{display:'inline',marginRight:8}}/>Execution policy</h2>{[['Execution','Paper simulation only'],['Position limit','2% of equity'],['Portfolio exposure','15% maximum'],['Drawdown stop','10% from peak'],['Independent clusters','3 eligible clusters'],['Minimum track record','20 observed round trips']].map(([k,v])=><div className="split listrow" key={k}><span className="muted">{k}</span><span>{v}</span></div>)}</section></div>
 <div className="grid"><section className="panel"><div className="split"><h2><Radio size={16} style={{display:'inline',marginRight:8}}/>Live evidence feed</h2><small className="muted">10s refresh</small></div><div className="feed">{events.length?events.slice(0,30).map((e:any)=><div className="event" key={e.id}><time>{time(e.at)}</time><div><strong>{e.type.replaceAll('_',' ')}</strong><p>{e.message}</p></div></div>):empty('Waiting for the first finalized block. No synthetic activity is shown.')}</div></section><section className="panel"><h2>Pipeline health</h2>{[['RPC',s?.provider??'Checking'],['Last successful cycle',time(s?.lastSuccess)],['Cycle duration',s?.latencyMs?`${(s.latencyMs/1000).toFixed(1)}s`:'—'],['Finalized slot',s?.cursor??'—'],['Lag behind chain',s?.lagSlots==null?'—':`${s.lagSlots} slots`],['Provider errors',s?.errors??0]].map(([k,v])=><div className="split listrow" key={k}><span className="muted">{k}</span><span className="mono">{v}</span></div>)}<p className="muted" style={{fontSize:14,marginTop:20}}>USDC balance-delta trade candidates only. This collector does not cover the entire chain in real time.</p></section></div><section className="panel"><h2>Open paper positions</h2>{s?.positions.length?s.positions.map((p:any)=><div className="listrow split" key={p.mint}><span>{short(p.mint)}</span><span>{money(p.qty*p.mark)} · {money(p.qty*p.mark-p.cost)} unrealized</span></div>):empty('No open positions. The engine waits for sufficient evidence.')}</section></TabsContent>
 <TabsContent value="signals"><div className="toolbar"><h2>Explainable opportunities</h2><span className="muted">{data?.signals.length??0} stored decisions</span></div>{data?.signals.length?<section className="panel"><Table><TableHeader><TableRow>{['Token','Score','Decision','Evidence',''].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{data.signals.map((x:any)=><TableRow key={x.id}><TableCell>{x.symbol}<small className="muted block">{time(x.at)}</small></TableCell><TableCell className="mono">{x.score}/100</TableCell><TableCell><span className={x.action==='REJECT'?'bad':'good'}>{x.action}</span></TableCell><TableCell>{x.reasons[0]??'Eligible wallet convergence'}</TableCell><TableCell><button className="btn" onClick={()=>setSelected({title:`Signal · ${x.symbol}`,...x})}>Inspect</button></TableCell></TableRow>)}</TableBody></Table></section>:empty('No signals evaluated yet. Recent discovered tokens enter the risk pipeline automatically.')}</TabsContent>
 <TabsContent value="wallets"><div className="toolbar"><h2>Wallet explorer</h2><input className="search" placeholder="Filter wallet address…" aria-label="Filter wallets" value={search} onChange={e=>setSearch(e.target.value)}/></div><section className="panel">{data?.wallets.length?<Table><TableHeader><TableRow>{['Wallet','Reputation','Confidence','Round trips','Estimated P&L',''].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{data.wallets.filter((w:any)=>w.wallet.includes(search)).map((w:any)=><TableRow key={w.wallet}><TableCell className="mono">{short(w.wallet)}</TableCell><TableCell>{w.score}/100</TableCell><TableCell>{pct(w.confidence)}</TableCell><TableCell>{w.roundTrips}</TableCell><TableCell className={w.pnl>=0?'good':'bad'}>{money(w.pnl)}</TableCell><TableCell><button className="btn" onClick={()=>setSelected({title:'Wallet evidence',...w})}>Inspect <ArrowUpRight size={12} style={{display:'inline'}}/></button></TableCell></TableRow>)}</TableBody></Table>:empty('Wallets are discovered from collected transactions, not a preset watchlist.')}<p className="muted" style={{fontSize:14}}>Estimated performance covers matched inventory within the collected window. A high score with low confidence is not eligible for trading.</p></section></TabsContent>
 <TabsContent value="tokens"><div className="toolbar"><h2>Token inspector</h2></div><section className="panel">{data?.tokens.length?data.tokens.map((t:any)=><div className="listrow split" key={t.mint}><div><b>{t.symbol}</b><p className="muted mono">{short(t.mint)}</p></div><div><small className="muted">Observed liquidity</small><p>{money(t.liquidity??0)}</p></div><button className="btn" onClick={()=>setSelected({title:`Token · ${t.symbol}`,...t})}>Full analysis</button></div>):empty('No token analysis yet. Mint authority, freeze authority, liquidity and concentration will appear here.')}</section></TabsContent>
 <TabsContent value="graph"><div className="toolbar"><h2>Wallet relationships</h2><span className="muted">Transfers ≠ shared ownership</span></div><section className="panel"><p className="muted">Direct SOL transfers are stored as weak links. They do not establish common control or independent confirmation.</p>{data?.edges.length?data.edges.slice(0,100).map((e:any)=><div className="listrow graph" key={e.id}><span className="node mono">{short(e.a)}</span><span className="muted">→ {e.kind} →</span><span className="node mono">{short(e.b)}</span><button className="btn" onClick={()=>setSelected({title:'Relationship evidence',...e})}>Evidence</button></div>):empty('No relationships observed yet.')}</section></TabsContent>
 <TabsContent value="decisions"><div className="toolbar"><input className="search" placeholder="Search decision log…" aria-label="Search decisions" value={search} onChange={e=>setSearch(e.target.value)}/><a className="btn" href="/api/export"><Download size={14} style={{display:'inline',marginRight:8}}/>Export evidence</a></div><section className="panel">{events.length?events.map((e:any)=><div className="event" key={e.id}><time>{time(e.at)}</time><div><strong>{e.type}</strong><p>{e.message}</p><button className="btn" onClick={()=>setSelected({title:'Decision record',...e})}>Raw record</button></div></div>):empty('The persistent decision log is empty.')}</section></TabsContent>
 <TabsContent value="experiments"><div className="toolbar"><h2>Reproducible evaluation</h2><button className="btn primary" onClick={replay} disabled={busy}>Replay collected evidence</button></div><div className="notice">Chronological replay includes costs, position exits and expanding walk-forward windows. Cash is the baseline. Sparse data or indicative market quotes cannot establish profitability.</div><div className="stats">{[['Hit rate',pct(data?.statistics.hitRate)],['Expectancy',data?.statistics.expectancy==null?'—':money(data.statistics.expectancy)],['Profit factor',data?.statistics.profitFactor?.toFixed(2)??'—'],['Simulated fees',money(s?.fees??0)]].map(([k,v])=><div className="stat" key={k}><label>{k}</label><strong>{v}</strong></div>)}</div><section className="panel">{data?.experiments.length?data.experiments.map((e:any)=><div className="listrow split" key={e.id}><div><b>{e.status.replaceAll('_',' ')}</b><p className="muted">{e.observations} observations · {e.signals} signals · {time(e.at)}</p></div><button className="btn" onClick={()=>setSelected({title:'Experiment report',...e})}>Inspect report</button></div>):empty('Run a replay to freeze the current dataset hash, policy version and evidence limits.')}</section></TabsContent>
 </Tabs><footer className="split"><span><Activity size={13} style={{display:'inline',marginRight:7}}/>ACTOR v1 · Evidence collection phase</span><span>Live signing unavailable · No keys stored · No profitability claim</span></footer></main>
 <Sheet open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><SheetContent className="overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle>{selected?.title??'Evidence'}</SheetTitle><SheetDescription>Persisted inputs, assumptions and provenance.</SheetDescription></SheetHeader><div style={{padding:20}}>{selected?.wallet&&<a href={`https://solscan.io/account/${selected.wallet}`} target="_blank" rel="noreferrer">View wallet on Solscan ↗</a>}<pre className="details">{JSON.stringify(selected,null,2)}</pre></div></SheetContent></Sheet></>}
