export const USDC='EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
export const POLICY={version:'convergence-v1',minRoundTrips:20,minLiquidity:100000,maxToken:0.02,maxExposure:0.15,maxDrawdown:0.1,latencyMs:1500,maxQuoteAge:60000,feeRate:0.003,spreadRate:0.002,networkFeeUSD:0.02,minClusters:3,minScore:70,maxHoldingMs:3600000};
export function tradesFromTransaction(tx:any,slot:number,at:number){
 if(!tx?.meta||tx.meta.err)return [];
 const keys=tx.transaction.message.accountKeys; const signers=new Set(keys.filter((k:any)=>k.signer).map((k:any)=>k.pubkey));
 const balances=new Map<string,Map<string,number>>();
 for(const [field,sign] of [['preTokenBalances',-1],['postTokenBalances',1]] as const)for(const b of tx.meta[field]??[]){if(!b.owner||!signers.has(b.owner))continue;const m=balances.get(b.owner)??new Map();const amount=Number(b.uiTokenAmount.amount)/10**b.uiTokenAmount.decimals;m.set(b.mint,(m.get(b.mint)??0)+sign*amount);balances.set(b.owner,m)}
 const out:any[]=[];for(const [wallet,m] of balances){const usd=m.get(USDC)??0;const others=[...m].filter(([mint,n])=>mint!==USDC&&Math.abs(n)>1e-9);if(Math.abs(usd)<0.01||others.length!==1)continue;const [mint,qty]=others[0];if(usd*qty>=0)continue;out.push({wallet,mint,side:qty>0?'buy':'sell',qty:Math.abs(qty),usd:Math.abs(usd),price:Math.abs(usd/qty),at,slot,signature:tx.transaction.signatures[0],feeLamports:tx.meta.fee,classification:'USDC balance-delta candidate; complex routes excluded'})}return out;
}
export function reputation(trades:any[]){let inv=new Map<string,{qty:number,cost:number}>(),pnl=0,wins=0,losses=0,grossWin=0,grossLoss=0;const returns:number[]=[];
 for(const t of [...trades].sort((a,b)=>a.at-b.at||a.slot-b.slot)){let p=inv.get(t.mint)??{qty:0,cost:0};if(t.side==='buy'){p.qty+=t.qty;p.cost+=t.usd*(1+POLICY.feeRate)+POLICY.networkFeeUSD}else if(p.qty>=t.qty&&p.qty>0){const cost=p.cost*t.qty/p.qty;const profit=t.usd*(1-POLICY.feeRate)-POLICY.networkFeeUSD-cost;p.qty-=t.qty;p.cost-=cost;pnl+=profit;returns.push(profit/cost);if(profit>0){wins++;grossWin+=profit}else{losses++;grossLoss-=profit}}inv.set(t.mint,p)}
 const n=wins+losses,mean=returns.reduce((a,b)=>a+b,0)/(n||1),score=Math.max(0,Math.min(100,50+25*Math.tanh(mean*5)+25*(2*(wins+2)/(n+4)-1)));return {score:Math.round(score),confidence:Math.min(1,n/100),roundTrips:n,pnl,wins,losses,profitFactor:grossLoss?grossWin/grossLoss:null,expectancy:mean,eligible:n>=POLICY.minRoundTrips&&score>=POLICY.minScore,label:'Observed-window estimate; incomplete inventory and transfers excluded'};
}
export function clusters(wallets:string[],edges:any[]){const parent=new Map(wallets.map(w=>[w,w]));const find=(w:string):string=>{if(!parent.has(w))parent.set(w,w);const p=parent.get(w)!;if(p===w)return w;const r=find(p);parent.set(w,r);return r};for(const e of edges){if(e.strength==='strong')parent.set(find(e.a),find(e.b))}return Object.fromEntries(wallets.map(w=>[w,find(w)]))}
export function tokenRisk(t:any){const reasons:string[]=[];if(!Number.isFinite(t.liquidity)||t.liquidity<POLICY.minLiquidity)reasons.push('Insufficient verified exit liquidity');if(t.mintAuthority!==null)reasons.push('Mint authority active or unknown');if(t.freezeAuthority!==null)reasons.push('Freeze authority active or unknown');if(t.top10===null||t.top10===undefined||t.top10>0.3)reasons.push('Top-10 token-account concentration >30% or unknown');if(t.program!=='TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA')reasons.push('Unsupported token program / extensions');if(!t.deployerVerified)reasons.push('Deployer and bundled supply history unverified');return {score:Math.max(0,100-reasons.length*18),allowed:reasons.length===0,reasons}}
export function signal(t:any,entries:any[],wallets:any[],groups:Record<string,string>,at:number){const eligible=entries.filter(e=>e.at<=at&&at-e.at<=300000&&e.side==='buy'&&wallets.find(w=>w.wallet===e.wallet)?.eligible);const independent=new Set(eligible.map(e=>groups[e.wallet]??e.wallet));const risk=tokenRisk(t);const reasons=[...risk.reasons];if(independent.size<POLICY.minClusters)reasons.push(`Only ${independent.size} eligible wallet clusters; need ${POLICY.minClusters}`);return {at,mint:t.mint,symbol:t.symbol,policy:POLICY.version,score:Math.round(risk.score*0.4+Math.min(1,independent.size/3)*60),action:reasons.length?'REJECT':'PAPER_BUY',reasons,evidence:{token:t,wallets:wallets.filter(w=>eligible.some(e=>e.wallet===w.wallet)),clusters:[...independent],entries:eligible},risk}}
export function fill(order:any,quote:any,at:number){if(at<order.at+POLICY.latencyMs)return {status:'pending'};if(!quote||quote.at<order.at+POLICY.latencyMs||at-quote.at>POLICY.maxQuoteAge||quote.price<=0||quote.liquidity<POLICY.minLiquidity)return {status:'failed',reason:'No fresh executable post-latency quote'};const impact=order.usd/(quote.liquidity/2);if(impact>0.02)return {status:'failed',reason:'Market impact exceeds 2%'};const adjustment=POLICY.spreadRate/2+impact;const price=quote.price*(order.side==='buy'?1+adjustment:1-adjustment);const fee=(order.side==='buy'?order.usd:order.qty*price)*POLICY.feeRate+POLICY.networkFeeUSD;return {status:'filled',price,fee,qty:order.side==='buy'?(order.usd-fee)/price:order.qty,slippage:adjustment,assumptions:{...POLICY},at}}
export function statistics(trades:any[],equity:any[]){const closed=trades.filter(t=>t.side==='sell'&&t.status==='filled'),wins=closed.filter(t=>t.pnl>0),losses=closed.filter(t=>t.pnl<=0),sum=(a:any[])=>a.reduce((s,t)=>s+t.pnl,0);let peak=equity[0]?.equity??1000,dd=0;for(const e of equity){peak=Math.max(peak,e.equity);dd=Math.max(dd,(peak-e.equity)/peak)}return {closed:closed.length,hitRate:closed.length?wins.length/closed.length:null,expectancy:closed.length?sum(closed)/closed.length:null,profitFactor:losses.length&&sum(losses)<0?sum(wins)/-sum(losses):null,averageWinner:wins.length?sum(wins)/wins.length:null,averageLoser:losses.length?sum(losses)/losses.length:null,maxDrawdown:dd,fees:trades.reduce((s,t)=>s+(t.fee??0),0),turnover:trades.reduce((s,t)=>s+(t.usd??0),0),sharpe:null,sharpeReason:'Requires a longer, regularly sampled return series'}}

// Chronological portfolio replay. Quotes are consumed in observed order, never
// searched ahead to determine entry quality or portfolio sizing.
export function replayPortfolio(signals:any[],quotes:any[],start:number,end:number,minScore=0){let cash=1000,peak=1000,halted=false;const positions=new Map<string,any>(),pending=new Map<string,any>(),trades:any[]=[],equity:any[]=[{at:start,equity:1000}];const events=[...signals.filter(s=>s.at>=start&&s.at<=end).map(s=>({...s,event:'signal'})),...quotes.filter(q=>q.at>=start&&q.at<=end).map(q=>({...q,event:'quote'}))].sort((a,b)=>a.at-b.at||(a.event==='quote'?-1:1));const value=()=>cash+[...positions.values()].reduce((s,p)=>s+p.qty*p.mark,0);
 for(const e of events){if(e.event==='signal'){if(e.action!=='PAPER_BUY'||e.score<minScore||halted||positions.has(e.mint)||pending.has(e.mint))continue;const total=value(),reserved=[...pending.values()].filter(o=>o.side==='buy').reduce((s,o)=>s+o.usd,0);const usd=Math.min(total*POLICY.maxToken,cash-reserved,total*POLICY.maxExposure-(total-cash)-reserved);if(usd>1)pending.set(e.mint,{mint:e.mint,at:e.at,side:'buy',usd,signalId:e.id});continue}
  const p=positions.get(e.mint);if(p&&Number.isFinite(e.price)&&e.price>0){p.mark=e.price;p.markAt=e.at}
  const o=pending.get(e.mint);if(o&&e.at>=o.at+POLICY.latencyMs){const f:any=fill(o,e,e.at);if(f.status!=='pending'){pending.delete(e.mint);if(f.status==='filled'){if(o.side==='buy'){if(o.usd>cash){trades.push({...o,status:'failed',reason:'Insufficient cash',at:e.at});continue}cash-=o.usd;positions.set(e.mint,{mint:e.mint,qty:f.qty,cost:o.usd,entry:f.price,mark:e.price,markAt:e.at,openedAt:e.at})}else if(p){const proceeds=p.qty*f.price-f.fee;f.pnl=proceeds-p.cost;cash+=proceeds;positions.delete(e.mint)}}trades.push({...o,...f,at:e.at})}}
  const total=value();peak=Math.max(peak,total);if((peak-total)/peak>=POLICY.maxDrawdown){halted=true;for(const [mint,o] of pending)if(o.side==='buy')pending.delete(mint)}
  const position=positions.get(e.mint);if(position&&!pending.has(e.mint)&&(halted||e.price/position.entry<=0.9||e.price/position.entry>=1.2||e.at-position.openedAt>=POLICY.maxHoldingMs))pending.set(e.mint,{mint:e.mint,side:'sell',qty:position.qty,usd:position.qty*e.price,at:e.at});equity.push({at:e.at,equity:value()});
 }
 const finalEquity=value();return {start,end,minScore,cash,finalEquity,return:finalEquity/1000-1,halted,trades,equity,openPositions:[...positions.values()],unresolvedOrders:[...pending.values()],statistics:statistics(trades,equity),valuationWarning:[...positions.values()].some(p=>end-p.markAt>POLICY.maxQuoteAge)?'Stale marks remain; reported equity is not realizable liquidation value':null};
}
export function walkForward(signals:any[],quotes:any[]){const dates=[...signals,...quotes].map(e=>e.at).filter(Number.isFinite).sort((a,b)=>a-b);if(dates.length<2)return {status:'INSUFFICIENT_EVIDENCE',folds:[],baseline:{strategy:'Cash',return:0}};const start=dates[0],end=dates.at(-1)!,step=(end-start)/4;if(step<=0)return {status:'INSUFFICIENT_EVIDENCE',folds:[],baseline:{strategy:'Cash',return:0}};const folds=[];for(let i=1;i<=3;i++){const split=start+step*i,stop=i===3?end:start+step*(i+1);const train=[70,80,90].map(score=>replayPortfolio(signals,quotes,start,split-1,score));const sufficient=train.some(t=>t.statistics.closed>=30);const selected=sufficient?[...train].filter(t=>t.statistics.closed>=30).sort((a,b)=>b.return-a.return)[0].minScore:80;const evaluation=replayPortfolio(signals,quotes,split,stop,selected);folds.push({trainStart:start,trainEnd:split-1,testStart:split,testEnd:stop,selectedMinScore:selected,selection:sufficient?'Training return; minimum 30 closed positions':'Fixed default; insufficient training trades',training:train.map(t=>({minScore:t.minScore,return:t.return,closed:t.statistics.closed})),evaluation})}return {status:folds.every(f=>f.evaluation.statistics.closed>=30)&&end-start>=30*86400000?'EVALUATED_UNVALIDATED':'INSUFFICIENT_EVIDENCE',folds,baseline:{strategy:'Cash',return:0},note:'Expanding training windows, nonoverlapping test windows, fresh paper account per fold. No strategy promotion is automatic.'}}
