-- AstraTrader hosted paper-runtime persistence.
-- Run once in the Supabase SQL Editor. These tables are server-only.

create table if not exists public.astratrader_meta (
  key text primary key,
  value text not null
);

create table if not exists public.astratrader_events (
  seq bigint generated by default as identity primary key,
  id text not null unique,
  at bigint not null,
  kind text not null,
  body text not null,
  prev text not null,
  hash text not null
);
create index if not exists astratrader_events_kind_seq on public.astratrader_events(kind, seq);

create table if not exists public.astratrader_jobs (
  id text primary key,
  body text not null,
  state text not null default 'pending',
  attempts integer not null default 0,
  available bigint not null,
  lease text,
  lease_until bigint
);
create index if not exists astratrader_jobs_pending on public.astratrader_jobs(state, available);

create table if not exists public.astratrader_observations (
  id text primary key,
  wallet text not null,
  mint text not null,
  at bigint not null,
  body text not null
);
create index if not exists astratrader_observations_wallet_at on public.astratrader_observations(wallet, at);
create index if not exists astratrader_observations_mint_at on public.astratrader_observations(mint, at);

create table if not exists public.astratrader_orders (
  id text primary key,
  state text not null,
  body text not null,
  updated bigint not null
);

create table if not exists public.astratrader_entities (
  kind text not null,
  id text not null,
  at bigint not null,
  body text not null,
  primary key(kind, id)
);
create index if not exists astratrader_entities_kind_at on public.astratrader_entities(kind, at);

create table if not exists public.astratrader_reservations (
  id text primary key,
  day text not null,
  amount bigint not null
);

alter table public.astratrader_meta enable row level security;
alter table public.astratrader_events enable row level security;
alter table public.astratrader_jobs enable row level security;
alter table public.astratrader_observations enable row level security;
alter table public.astratrader_orders enable row level security;
alter table public.astratrader_entities enable row level security;
alter table public.astratrader_reservations enable row level security;

-- Intentionally create no anon/authenticated policies. AstraTrader uses the
-- service-role key only on the server; never expose that key to the browser.
